blog_shueisha/blog_shueisha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_shueisha/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

"""En esta sección se encuenyran las urls de acceso a las páginas para lograr visialuzar el contenido de la web"""

app_name = "main"

urlpatterns = [
# Sección principales para la vista de blos y reviews creadas
	path('', views.IndexView.as_view(), name="home"),
	path('blogs/', views.PortfolioView.as_view(), name="blogs"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('reviews/', views.BlogView.as_view(), name="reviews"),
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),

# Sección para la cuenta de usuario, Login, Register, Logout
	path('register/', views.registerPage, name="register"),
	path('accounts/login/', views.loginPage, name= "login"),
	path('logout/', views.logoutUser, name="logout"),

# Sección para las principales partes para crear nuevos blos o reviews pero con restricciones de usuario para lograr crear
	path('blogaddinfo/', login_required(views.BlogAddInfo.as_view()), name='blogaddinfo'),
	path('reviewaddinfo/', login_required(views.ReviewAddInfo.as_view()), name='reviewaddinfo'),
	
	]

    

blog_shueisha/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

"""En esta seccion se plantean todos los modelos de los registros que va a tener la base de"""

# Modelo para almacenar los usuarios creados, donde se incluyen todos los campos que debe tener ese Usuario
class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


# Modelo para almacenar archivos de imagenes que se cargan dentro de la página
class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

# Modelo para almacenar los blogs registrados en la web
class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]

# Campos necesarios para registrar un nuevo blog de algún anime o manga
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


# Modelo para almacenar las reviews registradas y las nuevas ingresadas por nuevos usuarios.
class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

# Campos que deben ser llenados para las reviews
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"

blog_shueisha/main/forms.py
from django import forms
from .models import Blog

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

"""En Esta seccion se colocan todos los formularios que son utilizados para obtener información ingresada por el usuario"""


# Formulario para que el usuario pueda ingresar una nueva review de algún anime o manga
class ReviewForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,			# Campo para el author de la review del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,			# Campo para el Nombre del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,	# Campo para la descripcion
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,			# Campo para el contenido de la review
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()										# Campo para subir una imagen del anime

	class Meta:
		model = Blog
		fields = ['author', 'name', 'description', 'body', 'image']

# Formulario para ingresar un nuevo blog de anime o manga
class BlogForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,  
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()

	class Meta:
		model = Blog
		fields = ['author', 'name', 'description', 'body', 'image']

# Formulario para crear un nuevo usuario en el sistema
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password', 'password2']

blog_shueisha/main/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import (
		UserProfile,
		Blog,
		Portfolio,
	)

from django.views import generic
from . forms import CreateUserForm, BlogForm, ReviewForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect

"""En esta sección se encuentran las partes de las vistas y metodos para la correcta visualización de la web"""

# Función para lograr que un usuario se registre en el sistema 
def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('main>login')

		context = {'form':form}
		return render(request, 'main/register.html', context)

# Función para lograr ingresar dentro del sistema, validando los credenciales
def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username Or password is incorrect')

		context = {}
		return render(request, 'main/login.html', context)


# Función para cerrar la cesión 
def logoutUser(request):
	logout(request)
	return redirect('main:login')

# Vista para crear nuevos blogs en el sitio
class BlogAddInfo(generic.FormView):
	template_name = "main/blogaddinfo.html"
	form_class = ReviewForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you for contribute with the page :)')
		return super().form_valid(form)

# Vista para crear nuevas reviews para la página
class ReviewAddInfo(generic.FormView):
	template_name = "main/blogaddinfo.html"
	form_class = ReviewForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you for contribute with the page :)')
		return super().form_valid(form)

# Vista principal o menú de home donde se muestra el contenido principal de la web
class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
	
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True)

		context["blogs"] = blogs
		context["portfolio"] = portfolio
		return context

# Vista de portafolio donde se observan todos los blogs creados
class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

# Vista para ver los detalles de un blog
class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"

# Vista para ver las reviews creadas 
class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

# Vista para ver los detalles de una review
class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"

blog_shueisha/main/templates/main/base.html
{% load static %}
<!doctype html>
< lang="en">
  <>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/icon.jpg' %}">
    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'CSS/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'CSS/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'main/partials/messages.html' %}
    {% include 'main/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'main/partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{%endblock%}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

blog_shueisha/main/templates/main/blog-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name|title}}</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <div class="authorCol">
            <h4 class="smTitle pb-3">{{object.author|title}}</h4>
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">{{object.timestamp.date}}</h4>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm">
    <div class="container">
      {{object.body|safe}}
    </div>
  </div>
</section>

{% endblock %}
<!-- ================================
End Content
================================= -->
   

blog_shueisha/main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-60">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Resumen de Animes</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:blog' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%} 
    

blog_shueisha/main/templates/main/blogaddinfo.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Añada un nuevo blog</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="BlogForm" method="POST" action="{% url 'main:blogaddinfo' %}" enctype="multipart/form-data">
        {% csrf_token %}
            <label for="author">Author</label>
            {{form.author}}

            <label for="name">Name</label>
            {{form.name}}

            <label for="description">Description</label>
            {{form.description}}

            <label for="body">Body</label>
            {{form.body}}

            <label for="image">image</label>
            {{form.image}}
            <br>
            <br>

            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}
    

blog_shueisha/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section>
  <div class="bgContiner px 5">
    <div class="container px-20">
      <div class="row gx-5 justify-content-center">
          <div class="col-lg-6">
              <div class="text-center my-5">
                  <h1 class="display-5 fw-bolder text-white mb-2">SHUEISHA BLOGS </h1>
                  <p class="lead text-white-50 mb-4">Blogs y reviews de Animes y Mangas</p>
                  <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                      <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#contenido"></a>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

<section>
  <div class="sectionSpace" id="contenido">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Animes y Mangas Destacados</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'main:blogs' %}" class="simpleLink">View all</a>
          </div>
        </div>
        {% for p in portfolio %}
        {% if p.is_active %}
        <div class="portfolioCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                <a href="{% url 'main:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{% url 'main:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="portfolioOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        
      </div>
      
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Recent posts</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'main:blogs' %}" class="simpleLink">View all</a>
        </div>
      </div>
      <div class="row g-3">
      {% for b in blogs %}
      {% if b.is_active %}
        <div class="col-lg-6">
          <div class="cardStyle1">
            <h4 class="mdTitle cs1Title"><a href="{% url 'main:blog' slug=b.slug %}">{{b.name}}</a></h4>
            <ul class="cardOptionCol">
              <li>{{b.timestamp.date}}</li>
              <li>{{b.author}}</li>
            </ul>
            <p>{{b.description}}</p>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</section>
{% endblock %}
<!-- ================================
End Content
================================= -->

blog_shueisha/main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section>
    <div class="innerPageBannerCol">
      <div class="container">
        <div class="row g-4 g-md-3  align-items-center">
          <div class="col-md-6">
            <div class="bannerContent">
              <h1 class="xlTitle pb-md-3">Login Section</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  


<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>

                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>

                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn btnPrimary" type="submit" value="Login">
                           </div> 
                </form>

            </div>

            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}			
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'main:register' %}" class="ml-2"> Sign Up</a>
                </div>
        
            </div>
        </div>
    </div>
</div>



{% endblock %}
<!-- ================================
End Content
================================= -->

blog_shueisha/main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-60">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Resumen de animes y mangas destacados</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:portfolio' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{% endblock%}    

blog_shueisha/main/templates/main/reviewaddinfo.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Añada una nueva Review</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="BlogForm" method="POST" action="{% url 'main:reviewaddinfo' %}" enctype="multipart/form-data">
        {% csrf_token %}
            <label for="author">Author</label>
            {{form.author}}

            <label for="name">Name</label>
            {{form.name}}

            <label for="description">Description</label>
            {{form.description}}

            <label for="body">Body</label>
            {{form.body}}

            <label for="image">image</label>
            {{form.image}}
            <br>
            <br>

            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}
    