blog_shueisha/blog_shueisha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_shueisha/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

"""En esta sección se encuenyran las urls de acceso a las páginas para lograr visialuzar el contenido de la web"""

app_name = "main"

urlpatterns = [
# Sección principales para la vista de blos y reviews creadas
	path('', views.IndexView.as_view(), name="home"),
	path('blogs/', views.PortfolioView.as_view(), name="blogs"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('reviews/', views.BlogView.as_view(), name="reviews"),
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),

# Sección para la cuenta de usuario, Login, Register, Logout
	path('register/', views.registerPage, name="register"),
	path('accounts/login/', views.loginPage, name= "login"),
	path('logout/', views.logoutUser, name="logout"),

# Sección para las principales partes para crear nuevos blos o reviews pero con restricciones de usuario para lograr crear
	path('blogaddinfo/', login_required(views.BlogAddInfo.as_view()), name='blogaddinfo'),
	path('reviewaddinfo/', login_required(views.ReviewAddInfo.as_view()), name='reviewaddinfo'),
	
	]

    

blog_shueisha/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

"""En esta seccion se plantean todos los modelos de los registros que va a tener la base de"""

# Modelo para almacenar los usuarios creados, donde se incluyen todos los campos que debe tener ese Usuario
class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


# Modelo para almacenar archivos de imagenes que se cargan dentro de la página
class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

# Modelo para almacenar los blogs registrados en la web
class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]

# Campos necesarios para registrar un nuevo blog de algún anime o manga
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


# Modelo para almacenar las reviews registradas y las nuevas ingresadas por nuevos usuarios.
class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

# Campos que deben ser llenados para las reviews
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"

blog_shueisha/main/forms.py
from django import forms
from .models import Blog

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

"""En Esta seccion se colocan todos los formularios que son utilizados para obtener información ingresada por el usuario"""


# Formulario para que el usuario pueda ingresar una nueva review de algún anime o manga
class ReviewForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,			# Campo para el author de la review del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,			# Campo para el Nombre del anime
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,	# Campo para la descripcion
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,			# Campo para el contenido de la review
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()										# Campo para subir una imagen del anime

	class Meta:
		model = Blog
		fields = ['author', 'name', 'description', 'body', 'image']

# Formulario para ingresar un nuevo blog de anime o manga
class BlogForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,  
		widget=forms.TextInput(attrs={
			'placeholder': '*Author name..',
			}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	description = forms.CharField(max_length=500, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Description info..',
			}))
	body = forms.CharField(max_length=500, required=True,
		widget=forms.Textarea(attrs={
			'placeholder': '*Body info..',
			}))
	image = forms.ImageField()

	class Meta:
		model = Blog
		fields = ['author', 'name', 'description', 'body', 'image']

# Formulario para crear un nuevo usuario en el sistema
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password', 'password2']

blog_shueisha/main/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import (
		UserProfile,
		Blog,
		Portfolio,
	)

from django.views import generic
from . forms import CreateUserForm, BlogForm, ReviewForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect

"""En esta sección se encuentran las partes de las vistas y metodos para la correcta visualización de la web"""

# Función para lograr que un usuario se registre en el sistema 
def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('main>login')

		context = {'form':form}
		return render(request, 'main/register.html', context)

# Función para lograr ingresar dentro del sistema, validando los credenciales
def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username Or password is incorrect')

		context = {}
		return render(request, 'main/login.html', context)


# Función para cerrar la cesión 
def logoutUser(request):
	logout(request)
	return redirect('main:login')

# Vista para crear nuevos blogs en el sitio
class BlogAddInfo(generic.FormView):
	template_name = "main/blogaddinfo.html"
	form_class = ReviewForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you for contribute with the page :)')
		return super().form_valid(form)

# Vista para crear nuevas reviews para la página
class ReviewAddInfo(generic.FormView):
	template_name = "main/blogaddinfo.html"
	form_class = ReviewForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you for contribute with the page :)')
		return super().form_valid(form)

# Vista principal o menú de home donde se muestra el contenido principal de la web
class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
	
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True)

		context["blogs"] = blogs
		context["portfolio"] = portfolio
		return context

# Vista de portafolio donde se observan todos los blogs creados
class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

# Vista para ver los detalles de un blog
class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"

# Vista para ver las reviews creadas 
class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

# Vista para ver los detalles de una review
class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"

blog_shueisha/main/templates/main/partials/footer.html
{% load static %}
<!-- ================================
Start Footer
================================= -->
<footer>
    <div class="footerCol">
    <div class="container">
        <ul class="socialCol">
        <li><a href="javascript:void(0)"><img src="{% static 'images/facebook.png' %}" alt="..."></a></li>
        <li><a href="javascript:void(0)"><img src="{% static 'images/instagram.png' %}" alt="..."></a></li>
        <li><a href="javascript:void(0)"><img src="{% static 'images/gorjeo.png' %}" alt="..."></a></li>
        <li><a href="javascript:void(0)"><img src="{% static 'images/linkedin.png' %}" alt="..."></a></li>
        </ul>
        <div class="copyrightCol">
        <p>Copyright ©{% now 'Y' %} All rights reserved. Designed by <a href="https://jamesgrangerdesign.co.uk/" target="_blank">Designer</a></p>
        </div>
    </div>
    </div>
</footer>
<!-- ================================
End Footer
================================= -->

blog_shueisha/main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

blog_shueisha/main/templates/main/partials/nav.html
{% load static %}
<!-- ================================
Start Navigation Bar
================================= -->
<header>
    <div class="headerCol">
    <div class="container-fluid">
        <div class="row align-items-center">
        <div class="col-auto">
            <div class="logoCol"><a href="{% url 'main:home' %}"><img src="{% static 'images/new.png' %}" alt="..."></a></div>
        </div>
        <h1 class="nombre">Shueisha Blogs</h1>
        <div class="col">
            <div class="d-md-none">
            <button class="navToggle">
                <span class="navToggle__text">Toggle Menu</span>
            </button>
            </div>
            <div class="navCollapseCol">
            <div class="navCol">
                <ul>
                <li><a href="{%url 'main:home'%}">Home</a></li>
                <li><a href="{%url 'main:blogs' %}">Blogs</a></li>
                <li><a href="{% url 'main:reviews' %}">Reviews</a></li>
                <li>
                    <div class="dropdown">
                        <div class="dropdown-select">
                            <span class="select">Create</span>
                            <i class="fa fa-caret-down icon"></i>
                        </div>
                        <div class="dropdown-list">
                            <div><a class="dropdown-list_item" href="{%url 'main:blogaddinfo'%}">Blog Add</a></div>
                            <div><a class="dropdown-list_item" href="{%url 'main:reviewaddinfo'%}">Review Add</a></div>
                        </div>
                    </div>
                </li>
                
                <li>
                    <div class="dropdown">
                        <div class="dropdown-select">
                            <span class="select">Login</span>
                            <i class="fa fa-caret-down icon"></i>
                        </div>
                        <div class="dropdown-list">
                            <div><a class="dropdown-list_item" href="{%url 'main:login'%}">Sign In</a></div>
                            <div><a class="dropdown-list_item" href="{%url 'main:register'%}">Sign Up</a></div>
                        </div>
                    </div>
                </li>
                <li><a href="{%url 'main:logout'%}">Logout</a></li>
                </ul>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</header>
<!-- ================================
End Navigation Bar
================================= -->